name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version:
          - 28.1
          - snapshot

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install melpazoid
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid

    - name: Run melpazoid
      env:
        LOCAL_REPO: ${{ github.workspace }}
        # RECIPE is your recipe as written for MELPA:
        RECIPE: (eca :repo "editor-code-assistant/eca-emacs" :fetcher github)
        # set this to false (or remove it) if the package isn't on MELPA:
        EXIST_OK: false
      run: echo $GITHUB_REF && make -C ~/melpazoid
